name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name you are committing the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main
          FOLDER: /home/runner/work/SmiloSphere/SmiloSphere
          GITHUB_TOKEN: ${{ secrets.PAT }} # Use the personal access token instead of the default GITHUB_TOKEN
          MESSAGE: "Build: ({sha}) {msg}"

